<center><h1>INF-552 Lab 0</h1></center>
<br>
<center><font size="4">Introduction to Basic Development Tools</font></center>
<center><font size="3"><strong>Name</font></center>
<center><font size="3"><strong>USCID:</font></center>

### Rules

1. Please read the instructions and problem prompts **carefully**.
2. This lab is to give you some basic APIs of numpy, pandas and scikit-learn. Besides, some topics such as how to make your jupyter notebook be a more efficient developing tools, how to use git and GitHub will also be covered. The lab is to be done individually. You may talk to your fellow classmates about general issues ("Remind me again: Which API should I used for doing group by operation to a data set") but about the specifies of how to do these exercises.
3. Along with a similar vein, you can ask the TA for help, but ask questions about **concepts** but not ask the TA to help you debug your code. The TA is here to help, but not to do the work for you.
4. You are welcome to use the class resources and the Internet.
5. Playing with variations. Solve one problems, and then copy the code to a new cell and play around with it. Doing this is the single most important thing when learning programming.
6. This lab will not be graded but the content is highly related to your future programming assignments. So, treat it wisely.
7. All the content having been gone though in the week 1 discussion is just a snapshot of the most basic concepts. **You need to keep study more about Git, GitHub, Pandas, Numpy and Scikit-Learn in order to finish your programming assignments successfully.**
8. Have fun!

### Setup Development Environment

There are many ways to setup the environment. But, I do recommend a simple idea that is using the Anaconda, which is a pre-build python environment with bundles of useful packages.

**To download the Anaconda, go to the following website:
https://www.anaconda.com/distribution/**. Download the correct version based on your operating system and install it step by step.

Then, **configure your PATH environment variable** to make the conda command work. The following command is an easy way to test whether your configuration is correct. If it is, you will see something as like as the sample output.

> **command:**
>
> conda --version
>
> **sample output:**
>
> conda 4.6.12

**Finally, download this jupyter notebook file,** then change the working directory to where its location in terminal, and type the following command to open the jupter notebook and finish the lab.

> **command:** 
> jupyter notebook

In [1]:
# pip install -r requirements.txt

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import seaborn as sns

### Pandas

#### The read_csv() Method

First, read the documentation about the *read_csv()* method in Pandas (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Then, try to read data from file Salaries.csv to a dataframe, make the column playerID in the csv file as the index column and the first row as the header. Also, skip the second row when reading the file.

In [3]:
df_original = pd.read_csv('../data/Salaries.csv')
df_original.info()
# df_original.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25575 entries, 0 to 25574
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   yearID    25575 non-null  int64 
 1   teamID    25575 non-null  object
 2   lgID      25575 non-null  object
 3   playerID  25575 non-null  object
 4   salary    25575 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 999.2+ KB


In [4]:
df = pd.read_csv('../data/Salaries.csv',index_col='playerID',skiprows=[1]) 
df.head()

,yearID,teamID,lgID,salary
playerID,,,,
bedrost01,1985,ATL,NL,550000
benedbr01,1985,ATL,NL,545000
campri01,1985,ATL,NL,633333
ceronri01,1985,ATL,NL,625000
chambch01,1985,ATL,NL,800000


In [5]:
# df_2 = df.rename_axis(None)
# df_2.head()

#### Indexing and Selecting Data

Select the id of the players who are registered in ATL and HOU and whose salary is higher than one million.

In [6]:
greater_than_1mil = df.loc[((df.teamID=='ATL') | (df.teamID=='HOU')) & (df.salary > 1000000)]
print('Number of players with ALT or HOU having salary greater than 1 million: ', greater_than_1mil.shape[0])
print(greater_than_1mil)

Number of players with ALT or HOU having salary greater than 1 million:  595
           yearID teamID lgID   salary
playerID                              
hornebo01    1985    ATL   NL  1500000
murphda05    1985    ATL   NL  1625000
suttebr01    1985    ATL   NL  1354167
ryanno01     1985    HOU   NL  1350000
hornebo01    1986    ATL   NL  1800000
...           ...    ...  ...      ...
quallch01    2015    HOU   AL  3000000
rasmuco01    2015    HOU   AL  8000000
singljo02    2015    HOU   AL  2000000
sippto01     2015    HOU   AL  2400000
valbulu01    2015    HOU   AL  4200000

[595 rows x 4 columns]


#### The describe() Method

Calculate the standard Deviation, first quartile, medium, third quartile, mean, maximum, minimum of the salary in team ATL.

In [ ]:
# # df.loc[df.teamID=='ATL'].head()
data_ATL = df[(df.teamID=='ATL')]
# data_ATL_std = data_ATL.std(axis=0)
# print('Standard Deviation of team ATL salary is : ', data_ATL_std.salary)

data_ATL_quartile = data_ATL['salary'].quantile([0.25, 0.5, 0.75])
print('First and Third Quartiles, median of team ATL salary is : \n', data_ATL_quartile)

In [ ]:
df.loc[df.teamID=='ATL'].salary.describe()

#### The iterrows() Method

Create a Python dictionary object whose keys are the headers of the dataframe created in the read_csv() exercise and values are Python list objects that contain data corresponding to the headers. (Here, use the iterrows method to iterate each row of the dataframe and copy it to a dictionary. However, there is a easier way. Learn how the to_dict() method works by yourself later)

In [ ]:
df_temp = df.reset_index()
df_temp.head()

In [ ]:
temp_dict = {}
for header in df_temp.columns.values:
    temp_list = []
    for i, row in df_temp.iterrows():
        temp_list.append(row[header])
        temp_dict[header]=temp_list       

In [ ]:
# case_list = []
# for index, row in df_temp.iterrows():
#     my_dict = { index: row}
#     case_list.append(my_dict)
# print(case_list[0:5])

#### to_dict() method

In [ ]:
# method 1
# temp_dict2=df_temp.set_index('playerID').to_dict('list')

# method 2
result = df_temp.to_dict(orient = 'records')
print(result[0:2])

#### Create Dataframe Using the Constructor

Read the documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame and create a dataframe using pd.DataFrame from the dictionary created in the iterrows() exercise. Change the header to "a", "b", "c", ... at creation time.

In [ ]:
df_new = ""
# df_new = pd.DataFrame(data=temp_dict).rename({'playerID': 'a', 'yearID': 'b', 'teamID': 'c', 'lgID': 'd', 'salary': 'e'}, axis=1)
df_new = pd.DataFrame(result)
df_new.columns = ['a','b','c','d','e']

df_new.head()

In [ ]:
# df_new = pd.DataFrame(temp_dict,index = player_list, columns=list("ABCD"))
# df_new.head()

### Numpy

Quick start: https://www.numpy.org/devdocs/user/quickstart.html

Numpy axes explaination: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

#### The np.array Method

Example 1:

```python
ls = [1, 2, 3]
arr = np.array(ls)
```

Example 2:
```python
>>> np.array([[1, 2], [3, 4]])
array([[1, 2],
       [3, 4]])
```

Now, create a 2-dimensional Python list object, then convert it to a Numpy array object.

In [ ]:
ls = [[1,2,3],[4,5,6]]
print(ls)
print(type(ls))

In [ ]:
arr = np.array(ls)
print(arr)
print(type(arr))

#### ndarray Objects' Attributes

Play with the **ndim, shape, size, dtype, itemsize and data** attribute.

Example:

```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.ndim
2
```

#### ndim

In [ ]:
arr = np.array([[1, 2], [3, 4]])

In [ ]:
arr.ndim

#### shape

In [ ]:
arr.shape

#### size

In [ ]:
arr.size

#### dtype

In [ ]:
arr.dtype

#### itemsize

In [ ]:
arr.itemsize

#### data

In [ ]:
arr.data

#### Dimension of ndarray Ojects

Play with the reshape() and flatten() method.

Example:
```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.flatten()
array([1, 2, 3, 4])
```

In [ ]:
arr = np.array([[1, 2], [3, 4]])
arr.flatten()

In [ ]:
arr.reshape(2,2)

#### The Slice Operation of ndarray Objects

Understand how the slice operation works for 1-D array and 2-D array.

Example:

```python
>>> arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
>>> arr[1:]
array([[3, 4, 6],
       [7, 8, 9]])
>>> arr[1:, 0:2]
array([[3, 4],
       [7, 8]])
```

In [ ]:
arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
print(arr[1:])
print(arr[1:, 0:2])

#### The Calculation of ndarray Objects

Play with the **argmin(), argmax(), min(), max(), mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), mod()** method.

Example:

```python
>>> np.square(array)
array([[ 1,  4,  9],
       [ 9, 16, 36],
       [49, 64, 81]])

```

In [ ]:
arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
arr

#### argmin()

In [ ]:
print(np.argmin(arr))
print(np.argmin(arr,axis=0))
print(np.argmin(arr,axis=1))

#### argmax()

In [ ]:
np.argmax(arr)

#### min()

In [ ]:
np.min(arr)

#### max()

In [ ]:
np.max(arr)

#### mean()

In [ ]:
np.mean(arr)

#### sum()

In [ ]:
np.sum(arr)

#### std()

In [ ]:
np.std(arr)

#### dot()

In [ ]:
a =np.array([1,2])
b =np.array([2,1])
np.dot(a, b)

#### square()

In [ ]:
np.square(arr)

#### sqrt()

In [ ]:
b = np.square(arr)
np.sqrt(b)

#### abs()

In [ ]:
arr = np.array([[-1,-2],[-3,-4]])
print(arr)
print(np.abs(arr))

#### exp()

In [ ]:
arr = np.arange(4).reshape(2,2)
print(arr)
np.exp(arr)

#### sign()

In [ ]:
arr = np.array([[1,0],[-1,-1]])
np.sign(arr)

#### mod()

In [ ]:
np.mod([1,2],[2,1])

#### Other Important Methods Inside Module Numpy

Play with the arange(), ones(), zeros(), eye(), linspace(), concatenate() method.

Example:

```python
>>> np.eye(3)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

#### arange()

In [ ]:
np.arange(6)

#### ones()

In [ ]:
np.arange(6)

#### zeros

In [ ]:
np.zeros((2,2))

#### eye()

In [ ]:
np.eye(2)

#### linespace()

In [ ]:
np.linspace(1,5,num=10)

#### concatenate()

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

### Scikit-Learn

The followings are packages (or methods) in Python (Scikit-Learn and Scipy) that will be frequently used in your programming assignment. So, please read carefully.

- Data Preprocessing (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing)
    - Standardization: StandardScaler
    - Normalization: MinMaxScaler
    - Quantifing Categorical Features: LabelEncoder. OneHotEncoder
    - Construct Train and Test Set: model_selection.train_test_split
- KNN: KNeighborsClassifier
- Linear Regression: LinearRegression
- Logistic Regression: LogisticRegression, LogisticRegressionCV
- Feature Selection / Model Selection
    - L1 Penalized Regression (Lasso Regression) with Cross-Validation: LassoCV
    - L2 Penalized Regression (Ridge Regression) with Cross-Validation: RidgeCV
    - Cross-Validation: StratifiedKFold, RepeatedKFold, LeaveOneOut, KFold, model_selection.cross_validate, model_selection.cross_val_predict, model_selection.cross_val_score
    - Model Metrics (https://scikit-learn.org/stable/modules/classes.html#sklearn-metrics-metrics): accuracy_score, auc, f1_score, hamming_loss, precision_score, recall_score, roc_auc_score
- Decision Tree: DecisionTreeClassifier, DecisionTreeRegressor
- Bootstrap, Ensemble Methods
    - Bootstrap: bootstrapped (https://pypi.org/project/bootstrapped/)
    - Bagging: RandomForestClassifier, RandomForestRegressor
    - Boosting: AdaBoostClassifier, AdaBoostRegressor
- Support Vector Machines (https://scikit-learn.org/stable/modules/svm.html#svm): LinearSVC, LinearSVR
- Multiclass and Multilabel Classification (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.multiclass)
    - One-vs-one Multiclass Strategy: OneVsOneClassifier
    - One-vs-the-rest (OvR) multiclass/multilabel strategy / OneVsRestClassifier
- Unsupervised Learning
    - K-means Clustering: KMeans
    - Hierarchical Clustering: scipy.cluster.hierarchy (not scikit-learn)
- Semisupervised Learning (https://scikit-learn.org/stable/modules/label_propagation.html)

### Matplotlib

**Quick start:** https://matplotlib.org/3.1.1/tutorials/introductory/pyplot.html

**Exercises:**

(a) Create two one dimensional arrays x and y and plot y vs x, add title, xlabel, ylabel, grid.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y = np.array([j ** 2 for j in x])
```

copy the code above to the following cell and add code for plotting the parabola.

In [ ]:
# import numpy as np
# import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y = np.array([j ** 2 for j in x])

plt.plot(x,y)
plt.xlabel("x-label")
plt.ylabel("y-label")
plt.title("y vs x")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.show()

What happens if the independent variable is not sorted before plotting? Try plotting directly using the following defined array.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
np.random.shuffle(x)
y = np.array([j ** 2 for j in x])
```

In [ ]:
# import numpy as np
# import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
np.random.shuffle(x)
y = np.array([j ** 2 for j in x])



plt.plot(x,y)
plt.xlabel("x-label")
plt.ylabel("y-label")
plt.title("y vs x")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.show()

(b) Create multiple arrays and plot them with different styles, add legends, add text/mathematical equations on the plot.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y1 = np.array([j for j in x])
y2 = np.array([j ** 2 for j in x])
y3 = np.array([j ** 3 for j in x])
```

copy the code above to the following cell and add code for plotting curve $\left(x, y1\right)$, $\left(x, y2\right)$ and $\left(x, y3\right)$.

In [ ]:
# import numpy as np
# import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y1 = np.array([j for j in x])
y2 = np.array([j ** 2 for j in x])
y3 = np.array([j ** 3 for j in x])


plt.plot(x,y1, marker ='o', color='blue', label=r'y1=$x$')
plt.xlabel("x-label")
plt.ylabel("y-label")
plt.title("y1 vs x")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.legend(loc="lower right")
plt.show()

plt.plot(x,y2, marker='^', color='red', label=r'y2=$x^2$')
plt.xlabel("x-label")
plt.ylabel("y-label")
plt.title("y2 vs x")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.legend(loc="lower right")
plt.show()

plt.plot(x,y3, marker='d', color='orange',label=r'y3=$x^3$')
plt.xlabel("x-label")
plt.ylabel("y-label")
plt.title("y3 vs x")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.show()

(c) Create multiple arrays and plot them into one figure **(No multiple figure and no subplot is allowed in this question)**.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y1 = np.array([j for j in x])
y2 = np.array([j ** 2 for j in x])
y3 = np.array([j ** 3 for j in x])
```

copy the code above to the following cell and add code for plotting curve $\left(x, y1\right)$, $\left(x, y2\right)$ and $\left(x, y3\right)$.

In [ ]:
# import numpy as np
# import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y1 = np.array([j for j in x])
y2 = np.array([j ** 2 for j in x])
y3 = np.array([j ** 3 for j in x])


plt.plot(x,y1, marker ='o', color='blue', label=r'y1=$x$')
plt.plot(x,y2, marker='^', color='red', label=r'y2=$x^2$')
plt.plot(x,y3, marker='d', color='orange',label=r'y3=$x^3$')
plt.xlabel("x")
plt.ylabel("y")
plt.title("y1,y2,y3 vs x")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.legend(loc="lower right")
plt.show()

(d) Create multiple subplots, play around with the figure size, figure title, and its font style and font size **(One curve is plotted in one subplot in this question)**.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y1 = np.array([j for j in x])
y2 = np.array([j ** 2 for j in x])
y3 = np.array([j ** 3 for j in x])
```

copy the code above to the following cell and add code for plotting curve $\left(x, y1\right)$, $\left(x, y2\right)$ and $\left(x, y3\right)$.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y1 = np.array([j for j in x])
y2 = np.array([j ** 2 for j in x])
y3 = np.array([j ** 3 for j in x])



fig, axs = plt.subplots(3, figsize=(6,18))

axs[0].plot(x,y1, marker ='o', color='blue', label=r'y1=$x$')
axs[0].set_title("y1 vs. x", fontsize=15)

axs[1].plot(x,y2, marker='^', color='red', label=r'y2=$x^2$')
axs[1].set_title("y2 vs. x", fontsize=15)

axs[2].plot(x,y3, marker='d', color='orange',label=r'y3=$x^3$')
axs[2].set_title("y3 vs. x", fontsize=15)


for ax in axs:
#     ax.set(xlabel='x-label', ylabel='y-label')
    ax.set_xlabel('x-label',fontsize=15)
    ax.set_ylabel('y-label',fontsize=15)
    ax.grid(color='g', linestyle='--', linewidth=1)
    ax.legend(loc="lower right",prop={"size":15})
plt.show()

(e) Change the limits on x and y axes, **use logarithmic axes to plot**.

```python
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y = np.array([j ** 2 for j in x])
```

copy the code above to the following cell and add code for plotting the parabola.

In [ ]:
# import numpy as np
# import matplotlib.pyplot as plt


x = np.linspace(-5, 5, num=20)
y = np.array([j ** 2 for j in x])

plt.plot(x,y)
plt.xscale('log')
plt.yscale('log')
plt.xlabel("x-label")
plt.ylabel("y-label")
plt.title("y vs x")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.show()

### Pandas's DataFrame.plot and Seaborn

#### Pandas's DataFrame.plot

Use the Salaries.csv again (You can use the dataframe object loaded from section 3.1).

(a) For team 'ATL', plot a scatter plot between feature yearID and salary.

In [ ]:
df.head()

In [ ]:
df_ATL = df.loc[(df.teamID=='ATL')]

df_ATL.plot(kind='scatter',x='yearID',y='salary')
plt.title("salary vs. yearID")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.show()

(b) For year 1985, plot a bar chart to show the average salary for each team.

In [ ]:
df_1985 = df.loc[df.yearID==1985]
df_1985.groupby(['teamID']).salary.mean().plot(kind='bar')

plt.title("Average Salary vs. TeamID")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.ylabel("Average Salary")
plt.show()

(c) For team 'ATL', plot a line chart to show how the annual average salary change by years.

In [ ]:
df_ATL = df.loc[(df.teamID=='ATL')]
df_ATL.groupby(['yearID']).salary.mean().plot(kind='line')

plt.title("Average Salary vs. yearID")
plt.grid(color='g', linestyle='--', linewidth=1)
plt.ylabel("Average Salary")
plt.show()

#### Seaborn

(a) Append one more numeric feature to the data frame (can be generated randomly), then for team 'ATL', use the seaborn.pairplot to plot scatter plots among all numeric features in the data frame for team. 

In [ ]:
# import random
# import seaborn as sns

random_list = np.random.randint(18, 35, size=len(df.salary))

df['aveAge'] =  random_list
df.head()

g = sns.pairplot(df)
g.map(sns.scatterplot)

(b) For year 1985 and for each team, plot a boxplot to show how the salary distribute within a team.

In [ ]:
df_1985 = df.loc[df.yearID==1985]
df_1985.head()



# plt.figure(figsize=(12,6))
fig, ax = plt.subplots(figsize=(12,6))
sns.boxplot(x='teamID', y='salary', data=df_1985, orient='v')
fig.subplots_adjust(top=0.8)
ax.text(x=0.5,y=1.1, s="Boxplot of salary distribution for year 1985 of each team", fontsize=16, weight='bold', ha='center', va='bottom', transform=ax.transAxes)

(c) Read the offical documentation (https://seaborn.pydata.org/) to understand how lmplot, catplot, relplot, and jointplot works.

### Jupyter Notebook

#### Jupyter Notebook Extensions

Extensions such as the code formatter, table of content is to make your development more efficient. To explore it, please refer to https://github.com/ipython-contrib/jupyter_contrib_nbextensions.

#### Jupyter Visual Debugger

The Pixie Debugger is a visual debugger for debugging on Jupyter Notebook. To explore it, please refer to https://medium.com/codait/the-visual-python-debugger-for-jupyter-notebooks-youve-always-wanted-761713babc62.

### Git and GitHub

1. In the directory that where this jupyter notebook file locates in, init a Git repository.
2. Checkout a new branch called dev and commit the current notebook within this branch.
3. Merge the dev branch to the master branch (the default branch).
4. Create a temporary repository (just for practicing and you can delete it later) in GitHub. 
5. Push new changes in the master branch to the remote repository created in step 4.
6. Checkout the dev branch again and do some changes to your notebook, and then repeat step 3 and step 5.